sudo: required
services:
   - docker

before_install:
   - docker build -t mechenek/react-test -f ./client/Dockerfile.dev ./client

scripts:
   - docker run -e CI=true mechenek/react-test npm test

after_success:
   - docker build -t mechenek/multi-client ./client
   - docker build -t mechenek/multi-nginx ./nginx
   - docker build -t mechenek/multi-server ./server
   - docker build -t mechenek/multi-worker ./worker

   #Login to docker CLI
   - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

   # Push to docker hub
   - docker push mechenek/multi-client
   - docker push mechenek/multi-nginx
   - docker push mechenek/multi-server
   - docker push mechenek/multi-worker