sudo: required
services:
   - docker

before_install:
   - docker build -t wmedalla/multi-docker -f ./client/Dockerfile.dev ./client

scripts:
   - docker run -e CI=true wmedalla/multi-docker npm test

after_success:
   - docker build -t wmedalla/multi-client ./client
   - docker build -t wmedalla/multi-nginx ./nginx
   - docker build -t wmedalla/multi-server ./server
   - docker build -t wmedalla/multi-worker ./worker

#Login to docker CLI
- echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker hub
- docker push wmedalla/multi-client
- docker push wmedalla/multi-nginx
- docker push wmedalla/multi-server
- docker push wmedalla/multi-worker



